#include "..\script_component.hpp";
/* 
 * Author: CPL.Brostrom.A
 * This function initzialises all the default mission loadouts.
 *
 * Arguments:
 * None
 *
 * Example:
 * call cScripts_fnc_initAceLoadouts
 *
 * Public: No
 */

#ifdef DEBUG_MODE
    if !(is3DEN) then {
        ["Setting up CAV Default ACE Arsenal loadouts."] call FUNC(logInfo);
    } else {
        diag_log format["[%1] %2: %3", QUOTE(PREFIX), "INFO", "Setting up CAV Default ACE Arsenal loadouts in eden."];
    };
#endif

private _empty = [[],[],[],[],[],[],"","",[],["","","","","",""]];
["<empty>", _empty] call ace_arsenal_fnc_addDefaultLoadout;

["Platoon Leadership", [["rhs_weap_m4_carryhandle_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],"rhsusf_acc_rvg_blk"],[],[],["rhs_uniform_acu_oefcp",[["ACE_microDAGR",1],["ACE_quikclot",20],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_epinephrine",2],["ACE_EarPlugs",2],["ACE_morphine",2]]],["rhsusf_iotv_ocp_Squadleader",[["ACRE_PRC343",1],["ACRE_PRC152",2],["rhs_mag_m67",2,1],["SmokeShell",3,1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30]]],["B_AssaultPack_mcamo",[["ACE_EntrenchingTool",1],["ACE_personalAidKit",2],["ACE_CableTie",2],["ACE_HuntIR_monitor",1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",6,30],["Chemlight_red",2,1],["Chemlight_blue",2,1],["ACE_HuntIR_M203",4,1]]],"rhsusf_ach_helmet_headset_ess_ocp_alt","",["ACE_Vector","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Squad - Leader", [["rhs_weap_m4_carryhandle_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],"rhsusf_acc_rvg_blk"],[],[],["rhs_uniform_acu_oefcp",[["ACE_microDAGR",1],["ACE_quikclot",20],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_epinephrine",2],["ACE_EarPlugs",2],["ACE_morphine",2]]],["rhsusf_iotv_ocp_Squadleader",[["ACRE_PRC343",1],["ACRE_PRC152",1],["rhs_mag_m67",2,1],["SmokeShell",3,1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30]]],["B_AssaultPack_mcamo",[["ACE_EntrenchingTool",1],["ACE_personalAidKit",2],["ACE_CableTie",2],["ACE_HuntIR_monitor",1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",6,30],["Chemlight_red",2,1],["Chemlight_blue",2,1],["ACE_HuntIR_M203",4,1]]],"rhsusf_ach_helmet_headset_ess_ocp_alt","",["ACE_Vector","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Squad - Automatic Rifleman", [["rhs_weap_m249_pip","rhsusf_acc_SFMB556","","rhsusf_acc_ACOG_RMR",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_saw_bipod"],[],[],["rhs_uniform_acu_oefcp",[["ACE_microDAGR",1],["ACE_quikclot",20],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_epinephrine",2],["ACE_EarPlugs",2],["ACE_morphine",2]]],["rhsusf_iotv_ocp_SAW",[["ACRE_PRC343",1],["rhs_mag_m67",2,1],["SmokeShell",3,1],["rhs_mag_M433_HEDP",4,1],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",2,200]]],["B_AssaultPack_mcamo",[["ACE_EntrenchingTool",1],["ACE_personalAidKit",2],["ACE_CableTie",2],["Chemlight_red",2,1],["Chemlight_blue",2,1],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",2,200]]],"rhsusf_ach_helmet_headset_ess_ocp_alt","",["ACE_Vector","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Squad - Grenadier", [["rhs_weap_m4a1_m320","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],""],[],[],["rhs_uniform_acu_oefcp",[["ACE_microDAGR",1],["ACE_quikclot",20],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_epinephrine",2],["ACE_EarPlugs",2],["ACE_morphine",2]]],["rhsusf_iotv_ocp_Grenadier",[["ACRE_PRC343",1],["rhs_mag_m67",2,1],["SmokeShell",3,1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_M433_HEDP",4,1]]],["B_AssaultPack_mcamo",[["ACE_EntrenchingTool",1],["ACE_personalAidKit",2],["ACE_CableTie",2],["Chemlight_red",2,1],["Chemlight_blue",2,1],["rhs_mag_M441_HE",6,1],["rhs_mag_M397_HET",4,1],["ACE_40mm_Flare_red",2,1],["ACE_40mm_Flare_ir",2,1],["1Rnd_SmokeRed_Grenade_shell",4,1],["1Rnd_Smoke_Grenade_shell",4,1],["ACE_HuntIR_M203",2,1]]],"rhsusf_ach_helmet_headset_ess_ocp_alt","",["ACE_Vector","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Squad - Rifleman (m136)", [["rhs_weap_m4_carryhandle_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],"rhsusf_acc_rvg_blk"],["rhs_weap_M136","","","",[],[],""],[],["rhs_uniform_acu_oefcp",[["ACE_microDAGR",1],["ACE_quikclot",20],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_epinephrine",2],["ACE_EarPlugs",2],["ACE_morphine",2]]],["rhsusf_iotv_ocp_Rifleman",[["ACRE_PRC343",1],["rhs_mag_m67",2,1],["SmokeShell",3,1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30]]],["B_AssaultPack_mcamo",[["ACE_EntrenchingTool",1],["ACE_personalAidKit",2],["ACE_CableTie",2],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["Chemlight_red",2,1],["Chemlight_blue",2,1]]],"rhsusf_ach_helmet_headset_ess_ocp_alt","",["ACE_Vector","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Squad - Combat Life Saver", [["rhs_weap_m4_carryhandle_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],"rhsusf_acc_rvg_blk"],[],[],["rhs_uniform_acu_oefcp",[["ACE_microDAGR",1],["ACE_quikclot",20],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_epinephrine",2],["ACE_EarPlugs",2],["ACE_morphine",2]]],["rhsusf_iotv_ocp_Rifleman",[["ACRE_PRC343",1],["rhs_mag_m67",2,1],["SmokeShell",3,1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30]]],["B_AssaultPack_mcamo",[["ACE_EntrenchingTool",1],["ACE_personalAidKit",4],["ACE_CableTie",2],["ACE_quikclot",40],["ACE_morphine",6],["ACE_epinephrine",6],["ACE_tourniquet",8],["rhs_mag_30Rnd_556x45_Mk318_Stanag",4,30],["Chemlight_red",2,1],["Chemlight_blue",2,1]]],"rhsusf_ach_helmet_headset_ess_ocp_alt","",["ACE_Vector","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Longshot", [["rhs_weap_XM2010_d","rhsusf_acc_M2010S_d","rhsusf_acc_anpeq15side","rhsusf_acc_LEUPOLDMK4_2_d",["rhsusf_5Rnd_300winmag_xm2010",5],[],"rhsusf_acc_harris_bipod"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["rhs_uniform_acu_oefcp",[["ACE_microDAGR",1],["ACE_quikclot",20],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_epinephrine",2],["ACE_EarPlugs",2],["ACE_morphine",2]]],["rhsusf_iotv_ocp_Rifleman",[["ACRE_PRC343",1],["ACE_RangeCard",1],["rhs_mag_m67",2,1],["SmokeShell",3,1],["rhsusf_5Rnd_300winmag_xm2010",30,5],["rhsusf_mag_15Rnd_9x19_FMJ",6,15]]],["B_AssaultPack_mcamo",[["ACE_EntrenchingTool",1],["ACE_personalAidKit",2],["ACE_CableTie",2],["ACE_SpottingScope",1],["ACE_Tripod",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["Chemlight_red",2,1],["Chemlight_blue",2,1]]],"rhs_Booniehat_ocp","",["ACE_Vector","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","ACE_NVG_Wide"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Mustang", [["rhs_weap_m4_carryhandle_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],"rhsusf_acc_rvg_blk"],[],[],["rhs_uniform_acu_oefcp",[["ACE_microDAGR",1],["ACE_quikclot",20],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_epinephrine",2],["ACE_EarPlugs",2],["ACE_morphine",2]]],["rhsusf_iotv_ocp_Medic",[["ACRE_PRC343",1],["rhs_mag_m67",2,1],["SmokeShell",3,1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30]]],["B_Kitbag_mcamo",[["ACE_EntrenchingTool",1],["ACE_personalAidKit",6],["ACE_CableTie",2],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_tourniquet",12],["ACE_elasticBandage",60],["ACE_salineIV",8],["ACE_surgicalKit",1],["Chemlight_red",2,1],["Chemlight_blue",2,1]]],"rhsusf_ach_helmet_headset_ess_ocp_alt","",["ACE_Vector","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Apollo", [["rhs_m4a1_m203s_ACOG","","rhsusf_acc_anpeq15side","rhsusf_acc_ACOG",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],["rhs_mag_M585_white",1],""],[],[],["rhs_uniform_acu_oefcp",[["FirstAidKit",1],["rhsusf_ANPVS_14",1],["rhsusf_patrolcap_ocp",1],["I_IR_Grenade",1,1]]],["rhsusf_iotv_ocp_Grenadier",[["rhs_mag_30Rnd_556x45_M855A1_Stanag",3,30],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",3,30],["rhsusf_mag_15Rnd_9x19_FMJ",3,15],["rhs_mag_m715_Green",1,1],["rhs_mag_m661_green",1,1],["rhs_mag_m18_red",1,1],["rhs_mag_m18_green",1,1],["rhs_mag_m18_yellow",1,1],["rhs_mag_m18_purple",1,1],["Chemlight_green",1,1]]],["rhsusf_falconii_gr",[["rhs_mag_M433_HEDP",10,1],["rhs_mag_M585_white",5,1]]],"rhsusf_ach_helmet_camo_ocp","",["rhsusf_bino_lerca_1200_black","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]] call ace_arsenal_fnc_addDefaultLoadout;
["Havoc", [["rhs_weap_m4_carryhandle_mstock","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_eotech_xps3",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],"rhsusf_acc_rvg_blk"],[],[],["rhs_uniform_acu_oefcp",[["ACE_microDAGR",1],["ACE_quikclot",20],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_epinephrine",2],["ACE_EarPlugs",2],["ACE_morphine",2]]],["rhsusf_iotv_ocp_Repair",[["ACRE_PRC343",1],["ACE_DefusalKit",1],["ACE_Clacker",1],["ACE_M26_Clacker",1],["rhs_mag_m67",2,1],["SmokeShell",3,1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",7,30]]],["B_Kitbag_mcamo",[["ACE_EntrenchingTool",1],["ACE_personalAidKit",4],["ACE_CableTie",2],["Chemlight_red",2,1],["Chemlight_blue",2,1],["DemoCharge_Remote_Mag",4,1],["SatchelCharge_Remote_Mag",1,1]]],"rhsusf_ach_helmet_headset_ess_ocp_alt","",["ACE_Vector","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Sabre", [["rhsusf_weap_MP7A2","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_mrds",["rhsusf_mag_40Rnd_46x30_AP",40],[],"rhs_acc_grip_ffg2"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["rhs_uniform_acu_oefcp",[["ACE_quikclot",20],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellGreen",1,1],["Chemlight_green",1,1]]],["rhsusf_spcs_ocp_crewman",[["ACRE_PRC343",1],["ACRE_PRC152",2],["SmokeShellBlue",4,1],["SmokeShellOrange",4,1],["B_IR_Grenade",2,1],["rhs_mag_m67",2,1],["rhsusf_mag_40Rnd_46x30_AP",2,40],["rhsusf_mag_15Rnd_9x19_FMJ",2,15]]],["B_AssaultPack_mcamo",[["ToolKit",1],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",4],["ACE_personalAidKit",4],["rhsusf_mag_40Rnd_46x30_AP",2,40]]],"rhsusf_cvc_helmet","",[],["ItemMap","","","ItemCompass","ItemWatch","NVGoggles"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Banshee", [["rhsusf_weap_MP7A2","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_mrds",["rhsusf_mag_40Rnd_46x30_AP",40],[],"rhs_acc_grip_ffg2"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["rhs_uniform_acu_oefcp",[["ACE_quikclot",20],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellGreen",1,1],["Chemlight_green",1,1]]],["rhsusf_spcs_ocp_crewman",[["ACRE_PRC343",1],["ACRE_PRC152",2],["SmokeShellBlue",4,1],["SmokeShellOrange",4,1],["B_IR_Grenade",2,1],["rhs_mag_m67",2,1],["rhsusf_mag_40Rnd_46x30_AP",2,40],["rhsusf_mag_15Rnd_9x19_FMJ",2,15]]],["B_AssaultPack_mcamo",[["ToolKit",1],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",4],["ACE_personalAidKit",4],["rhsusf_mag_40Rnd_46x30_AP",2,40]]],"rhsusf_cvc_helmet","",[],["ItemMap","","","ItemCompass","ItemWatch","NVGoggles"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Buffallo", [["rhsusf_weap_MP7A2","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_mrds",["rhsusf_mag_40Rnd_46x30_AP",40],[],"rhs_acc_grip_ffg2"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["rhs_uniform_acu_oefcp",[["ACE_quikclot",20],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellGreen",1,1],["Chemlight_green",1,1]]],["rhsusf_spcs_ocp_crewman",[["ACRE_PRC343",1],["ACRE_PRC152",2],["SmokeShellBlue",4,1],["SmokeShellOrange",4,1],["B_IR_Grenade",2,1],["rhs_mag_m67",2,1],["rhsusf_mag_40Rnd_46x30_AP",2,40],["rhsusf_mag_15Rnd_9x19_FMJ",2,15]]],["B_AssaultPack_mcamo",[["ToolKit",1],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",4],["ACE_personalAidKit",4],["rhsusf_mag_40Rnd_46x30_AP",2,40]]],"rhsusf_hgu56p_visor_mask_black","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Raider", [["rhsusf_weap_MP7A2","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_mrds",["rhsusf_mag_40Rnd_46x30_AP",40],[],"rhs_acc_grip_ffg2"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["rhs_uniform_acu_oefcp",[["ACE_quikclot",20],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellGreen",1,1],["Chemlight_green",1,1]]],["rhsusf_spcs_ocp_crewman",[["ACRE_PRC343",1],["ACRE_PRC152",2],["SmokeShellBlue",4,1],["SmokeShellOrange",4,1],["B_IR_Grenade",2,1],["rhs_mag_m67",2,1],["rhsusf_mag_40Rnd_46x30_AP",2,40],["rhsusf_mag_15Rnd_9x19_FMJ",2,15]]],["B_AssaultPack_mcamo",[["ToolKit",1],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",4],["ACE_personalAidKit",4],["rhsusf_mag_40Rnd_46x30_AP",2,40]]],"rhsusf_hgu56p_visor_mask_black","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]] call ace_arsenal_fnc_addDefaultLoadout;
["Eagle", [[],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["U_B_PilotCoveralls",[["ACE_quikclot",20],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACRE_PRC152",2],["SmokeShellGreen",1,1],["Chemlight_green",1,1]]],[],["B_AssaultPack_blk",[["ToolKit",1],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",4],["ACE_personalAidKit",4]]],"H_PilotHelmetFighter_B","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]] call ace_arsenal_fnc_addDefaultLoadout;
["Titan", [[],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["U_B_PilotCoveralls",[["ACE_quikclot",20],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACRE_PRC152",2],["SmokeShellGreen",1,1],["Chemlight_green",1,1]]],[],["B_AssaultPack_blk",[["ToolKit",1],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",4],["ACE_personalAidKit",4]]],"H_PilotHelmetFighter_B","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]] call ace_arsenal_fnc_addDefaultLoadout;

#ifdef DEBUG_MODE
    if !(is3DEN) then {
            ["CAV Default ACE Arsenal loadouts completed."] call FUNC(logInfo);
    } else {
        diag_log format["[%1] %2: %3", QUOTE(PREFIX), "INFO", "CAV Default ACE Arsenal loadouts added in eden."];
    };
#endif
